conda_forge_output_validation: true

build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
os_version:
  linux_64: cos7

azure:
  # toggle for storing the conda build_artifacts directory (including the
  # built packages) as an Azure pipeline artifact that can be downloaded
  store_build_artifacts: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
